### ISSUE TITLE
Deploy every PR to Kubernetes

### ISSUE THREAD

**Issue by anneschuth** [MinBZK/ai-validation-infra#47]
# Intro
For AMT we could deploy every PR to kubernetes namespace `tn-ai-validation-amt-staging`. After the PR is merged we should destroy the kubernetes deployment. 

# Implementation notes
* service account with minimal permissions
* use github actions with a .kube/config containing information from the service account
* every object in the namespace has a unique name (including ingress which gives a unique url)

# Acceptance Criteria
* Every PR is deploy to Kubernetes
* Every PR is cleaned up in kubernetes after it is closed
* Additional action to clean up old (2 week old) resources.

**Comment by uittenbroekrobbert** [comment]
Digilab only supports the GitOps way of working. This means we can not use a service account to do deployments. The other solution is to create kustomize overlays (folders) for each PR in the infra branch and restructure the resources to allow for this re-use. This option might require more work and is less desirable.

For now it has been decided not to implement this feature, therefore this ticket will be closed.
